name: Continuous integration example

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy: 
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: ['11','17','21']
    name: Java ${{matrix.java}} sample
    steps: 
      - uses: action/checkout@v4
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v4
        with: 
          distribution: 'adopt'
          java-version: ${{matrix.java}}
      - run: mvn test
